. buffer.cpp: fixed a bug in Resize and ResizeWithOffset when the buffer size is bigger than the CBuffer's m_arrBuf, when the logic failed to realloc the memory because of a mistaken check to deny the realloc if the size of the content to keep is less than the size of m_arrBuf. It could result in memory currption when called from Append, since the memory was not get extended at all.
. iftasks.cpp: fixed a bug introduced by the last changes to CIfParallelTaskGrp,
that the return value was not returned correctly from RemoveTask.

. rpcf.cpp: added support to translate the `internet domain name' to a
normalized ip address, which become necessary when the connection is via a
websocket.

. wsport/Makefile.am: fixed an undefined reference to base64::encode because the
static lib libwsock.a came after libutils.a, and the linker cannot find the
symbol referred from libwsock.a.

. wsfido.cpp: guarded the m_pCurFrame with port lock, which was added when
chasing the CBuffer's bug, but showed no effect.

. rpcfg.py: fixed some bugs in websocket support.